### ISSUE TITLE
Could this support other languages as well?

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode-js-profile-visualizer#1] opened 2020-04-18 10:02 UTC
It would be great if this could support other languages than JS as well, it would be great if we could use that for the [Julia extension](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia). Presumably we would just need the ability to generate `*.cpuprofile` files?

If this could support other languages as well, could the branding/naming of the package ideally not use "JavaScript" too much? Just as an example, the description of one of the packages right now reads as "Flame graph visualizer for profiles taken from the JavaScript debugger".

**Comment by connor4312** [comment] 2020-04-20 16:36
It could. Right now this is still a bit of an exploration.

Soon (this month or next month) I'll be adding support for the other types of profiles that can be taken from JavaScript targets (https://github.com/microsoft/vscode-js-debug/issues/435). We'll become more generic at that point, which could open the door for visualizing other types of profiles. Or you could generate .cpuprofiles yourself--the format is fairly simple, happy to answer questions if you have any.

**Comment by davidanthoff** [comment] 2020-04-25 13:01
Yeah, I thought that we could just generate .cpuprofiles that seems the easiest option. I did google around a bit and found some info on the format, but nothing authorative. Do you have a link with a spec? Or just some good starting point to understand the details of the format?

**Comment by connor4312** [comment] 2020-04-25 17:07
This is the definition: https://chromedevtools.github.io/devtools-protocol/tot/Profiler/#type-Profile

**Comment by davidanthoff** [comment] 2020-05-05 18:48
Alright, I've got so far that I can export a Julia profile result as a .cpuprofile file that can be opened with the VS Code UI :) It is pretty incomplete, though, right now I'm not exporting the tree structure.

One thing that would be helpful is to understand which optional fields from the spec you need to have present for the UI to show something useful. I believe both `samples` and `timeDeltas` are needed, right?

What about `hitCount` and `positionTicks`?

Also, am I right that some of these fields essentially hold data that is kind of duplicate in the spec? I.e. couldn't something like `hitCount` be computed from just the data in `samples`?

**Comment by connor4312** [comment] 2020-05-05 18:55
Awesome!

Sample and timeDeltas are where we build most data from. I don't look at hitCount at all, I don't think it's included in recent versions of V8. positionTicks are used for displaying line information in the code lenses, you can get a glance of what they look like in the gif I made for the upcoming release: https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/images/1_45/js-debug-profiling.gif

Unfortunately "ticks" aren't directly correlated to time so they're not as clear to users as they could be (like, a certain number of ms per line). If Julia gives you wall clock time per-line you could just say 1 tick = 1ms... or wait until I support Tracing API profiles which have real per-line time and will require me to build support for that 🙂 

By the way, the table-based visualizer is now built-in on Insiders; if you run the `vscode.open` command on a cpuprofile, it will be displayed nicely for people on Insiders.

**Comment by davidanthoff** [comment] 2020-05-05 19:17
Ah, super helpful!

> By the way, the table-based visualizer is now built-in on Insiders

Yes, I found that, makes it _a lot_ easier to play with this :)

Another quick question: for a given `ProfileNode`, should `callFrame.lineNumber` and `callFrame.columnNumber` refer to the location of the function definition itself, right? Not a specific line inside the function, right?

And then, with `positionTicks`, is the idea that if I have a ProfileNode, and say that node appears `n` times in the `samples` array, then this node can have a number of elements in `positionTicks`, and the sum of the `ticks` for the entire `ProfileNode` should equal `n`?

**Comment by connor4312** [comment] 2020-05-05 19:25
> or a given ProfileNode, should callFrame.lineNumber and callFrame.columnNumber refer to the location of the function definition itself, right? 

Yep

> with positionTicks, is the idea that if I have a ProfileNode, and say that node appears n times in the samples array, then this node can have a number of elements in positionTicks, and the sum of the ticks for the entire ProfileNode should equal n?

I'm not sure actually, though that would make sense

**Comment by vchuravy** [comment] 2020-05-06 17:35
@connor4312 I hope you don't mind me asking more questions :) I was working on converting from Julia internal format to `.cpuprofile`.

We have a sampling profiler that provides backtraces/stackframes. Right now in https://github.com/davidanthoff/ChromeProfileFormat.jl/pull/3 I am converting each sampled stack frame into a linear sequence. Do I need to collapse these sequence onto each other so that they form trees? Each ProfileNode corresponds to a unique instruction pointer and so it only has one child. Is a ProfileNode in the Javascript world a single function? Each `positionTick` a location inside said function and each `child` the function called at said location?

**Comment by vchuravy** [comment] 2020-05-06 18:52
With my most recent changes (in which I tried out my comments above), I produced https://gist.github.com/vchuravy/c38cf8dd5118f7575359f648d0653e8e which breaks the viewer with a "CallStack exhausted message". But I could open it in https://www.speedscope.app/

**Comment by connor4312** [comment] 2020-05-06 19:06
It looks like there's a cycle in the profile you posted -- call frame 15 has frame 16 as a child, and 16 has 15 as a child.

> Do I need to collapse these sequence onto each other so that they form trees?

Sequence should have a unique set of nodes. For instance if I make a call from `foo() -> bar() -> baz()` and then from `oof() -> bar() -> baz()`, you should end up with 6 unique nodes (with 4 unique call frames)

**Comment by vchuravy** [comment] 2020-05-06 21:05
> It looks like there's a cycle in the profile you posted -- call frame 15 has frame 16 as a child, and 16 has 15 as a child.

Yeah there is recursion in the example. 

Okay gotcha. What about:

`foo():3 -> bar()`, `foo():5->bar()`. E.g. calls to the same function but on different lines? Should those be different nodes?

**Comment by connor4312** [comment] 2020-05-06 21:21
Yep, they should.

**Comment by connor4312** [comment] 2020-05-06 21:27
Those ones should be the same nodes.

**Comment by vchuravy** [comment] 2020-05-07 01:19
Okay thank you for the hints! I think I implemented that correctly, but the extension fails with "Cannot read property 'selfTime' of undefined" when loading https://gist.github.com/vchuravy/cd5729b94ed6d3a18e341d891a1a4c99 https://www.speedscope.app/ does load it, albeit not rendering the children of the top-level function... Manually inspecting my file it seems fine, so I am not sure what the issue is.

**Comment by vchuravy** [comment] 2020-05-08 00:12
After ironing out some of the kinks, I think I got it to work and an update of my VSCode got rid of the error message.

Now comparing a profile that I took from some code that runs in about ~50-60ms I noticed that VSCode seems to drop the top-most function in this case called `Main.profile_test` from both the table view and the flame graphs. Additionally the total time seems off. VSCode reports ~250ms whereas the code run in 50-60ms and speedscope got it right. Maybe I am emitting the wrong `positionTicks`? I emit one everytime I pass through that node in the graph for the line that is active.

![VSCode](https://user-images.githubusercontent.com/145258/81355954-fdc47f80-909d-11ea-8e81-a4d676f3b877.png)
![speedscope](https://user-images.githubusercontent.com/145258/81355956-fdc47f80-909d-11ea-9829-e5f0b91017ba.png)

![VSCode-sandwich](https://user-images.githubusercontent.com/145258/81355952-fd2be900-909d-11ea-8ccd-e0fc5cf41bb5.png)
![speedscope-sandwich](https://user-images.githubusercontent.com/145258/81355953-fdc47f80-909d-11ea-9485-f2308d6fe6d8.png)

The profile is available here (slightly different than the one in the screenshots). https://gist.github.com/vchuravy/b12d64ae069678a5ee35ff5618da3257

**Comment by connor4312** [comment] 2020-05-08 05:34
Nice! I don't think time difference is your fault, it's been on my todo for a little while. Super cool to see it working for you!

**Comment by jasonwilliams** [comment] 2020-06-02 09:28
in the Rust world we can measure rust binaries using [`measureme`](https://github.com/rust-lang/measureme) and [`crox`](https://github.com/rust-lang/measureme/blob/master/crox/Readme.md) which generates a chrome_profiler.json (this is the file you can upload to chrome performance).

I wonder if this could be shown in using this plugin?

I don't know what format this plugin needs but currently it generates the format Chrome performance Tab understands.

**Comment by connor4312** [comment] 2020-06-02 15:23
That looks like the "tracing" tab, which is a separate type of profile but on my todo.

**Comment by davidanthoff** [comment] 2020-07-11 17:49
We shipped a new Julia extension with support for this! See [here](https://discourse.julialang.org/t/julia-vs-code-extension-version-v0-17-released/42865).

**Comment by connor4312** [comment] 2020-07-11 17:51
Nice!

Also, table is fixed in https://github.com/microsoft/vscode-js-debug/issues/561 so I'll go ahead and close this issue.

Great work with the extension 🙂

**Closed by connor4312** 2020-07-11 17:51 UTC
