### ISSUE TITLE
Realtime graphs not showing

### ISSUE THREAD

**Issue by oguimbal** [microsoft/vscode-js-profile-visualizer#26] opened 2020-10-15 10:35 UTC
Hello,

The realtime graph is not showing while starting debugging.

I can however profile a session (and I can open the .cpuprofile files generated)
![image](https://user-images.githubusercontent.com/8973947/96111922-26209780-0ee2-11eb-9009-3abcc7e740ac.png)

nb1: Clicking on both debug sessions does not do anything.
nb2: I couldnt find anything suspect in extension logs (I could seach more if you tell me what to search for)
nb3: Here is the debug config I'm running:

```json
{
      "type": "node",
      "request": "launch",
      "name": "Webpack debug",
      "cwd": "${workspaceFolder}",
      "args": [
        "${workspaceFolder}/output/app-entry.js"
      ],
      "protocol": "inspector",
      "outputCapture": "std",
      "sourceMaps": true,
      "env": {
        "NODE_ENV": "development",
        "TZ": "utc",
      },
      "resolveSourceMapLocations": [
             ...
      ],
      "skipFiles": [
        "<node_internals>/**/*.js",
          .....
      ]
    }
```

[EDIT] Oh, if it's of any help, I'm running vscode on WSL2

**Comment by clementohNZ** [comment] 2020-10-21 02:57
Same issue for me.

**Comment by connor4312** [comment] 2020-10-21 03:07
@clementohNZ the view will only show if all of these are true:

1. You have [the extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-js-profile-flame) installed and enabled
1. You're debugging a node/chrome/extensionHost debug type
1. You don't have `debug.javascript.usePreview` set to `false`

**Comment by connor4312** [comment] 2020-10-21 03:08
@oguimbal it looks like the view shows and there's no the "no info" placeholder, so I wonder if there's some JavaScript error. Are any errors visible in the console when you run `Debug: Toggle Developer Tools`

**Comment by clementohNZ** [comment] 2020-10-21 10:00
@connor4312 Thanks for your reply. Just tested it with a dummy `index.js` file that starts an express server and it works. Just wondering how I can configure this to work with npm scripts such as `npm run start:dev`

**Comment by connor4312** [comment] 2020-10-21 15:46
It only shows up when you're debugging, since we essentially run a repl function over the debug protocol to get performance data for Node. There are a a few different ways you debug npm scripts (without needing a launch config ):

- Select `Debug: Node.js (preview)` from the debug menu, which will autodetect npm scripts
- Use the code lens that appears in your package.json to debug an npm scripts
- Use the Npm Scripts view in the explorer (use the "Focus on NPM Scripts View" command if you've hidden this before) which has a debug button
- or use the debug terminal via the "Create JavaScript Debug Terminal" command, and manually `npm run start:dev`

**Comment by clementohNZ** [comment] 2020-10-21 16:36
Awesome, the scripts view worked like a charm for the basic express app :)

When I tested it for Nest JS using `start:dev` script, it doesn't want to debug though. It exits the debugger immediately. The only way I can get it to debug the `start:dev` script is if I go to the `package.json` and debug the script by clicking the `debug` button and then selecting the script. When I do this however, the performance graph no longer shows up.

**Comment by connor4312** [comment] 2020-10-21 21:24
> When I tested it for Nest JS using start:dev script, it doesn't want to debug though. It exits the debugger immediately.

How were you running this?

> if I go to the package.json and debug the script by clicking the debug button and then selecting the script. When I do this however, the performance graph no longer shows up.

This is the same as https://github.com/microsoft/vscode-js-profile-visualizer/issues/24 -- now published that

**Comment by oguimbal** [comment] 2020-10-22 09:06
@connor4312 Nope. Not much in devtools :(

I only get this from time to time, but not systematically. Not sure it is related in any way.
nb: I tried to run a single js file `while(true){}`  ... same result. Its not related to my project.

```
 ERR No debugger available, can not send 'getPerformance': Error: No debugger available, can not send 'getPerformance'
    at N.customRequest (file:///C:/Users/Oliv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6154:759)
    at u.$customDebugAdapterRequest (file:///C:/Users/Oliv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4513:13)
    at p._doInvokeHandler (file:///C:/Users/Oliv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4599:202)
    at p._invokeHandler (file:///C:/Users/Oliv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4598:901)
    at p._receiveRequest (file:///C:/Users/Oliv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4597:510)
    at p._receiveOneMessage (file:///C:/Users/Oliv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4596:478)
```

**Comment by oguimbal** [comment] 2020-10-22 09:14
Oh, and I got this once, but never reproduced it:

![image](https://user-images.githubusercontent.com/8973947/96850880-a487b700-1457-11eb-8e5a-a2413b6d2d79.png)

**Comment by PhoenSXar** [comment] 2020-11-03 14:36
> @connor4312 Nope. Not much in devtools :(
> 
> I only get this from time to time, but not systematically. Not sure it is related in any way.
> nb: I tried to run a single js file `while(true){}` ... same result. Its not related to my project.
> 
> ```
>  ERR No debugger available, can not send 'getPerformance': Error: No debugger available, can not send 'getPerformance'
>     at N.customRequest (file:///C:/Users/Oliv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6154:759)
>     at u.$customDebugAdapterRequest (file:///C:/Users/Oliv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4513:13)
>     at p._doInvokeHandler (file:///C:/Users/Oliv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4599:202)
>     at p._invokeHandler (file:///C:/Users/Oliv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4598:901)
>     at p._receiveRequest (file:///C:/Users/Oliv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4597:510)
>     at p._receiveOneMessage (file:///C:/Users/Oliv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4596:478)
> ```
> 
> I also get that when starting vscode:
> 
> ```
> Extension Host
> localProcessExtensionHost.ts:258 [1022/110914.509:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
> ```
> 
> And as a sidenote, I tried both of these, with the same result:
> ![image](https://user-images.githubusercontent.com/8973947/96850729-71452800-1457-11eb-9905-4c4f08ab5112.png)

Same issue for me, I'm running vscode on windows 10, connected to a linux vm in Vmware Workstation by using Remote Development pack.
After read this issue, I opened my Developer Tools and found the 'No debugger available' ERR, but never reproduced it too.

**Comment by organic-scholar** [comment] 2021-05-15 21:59
I am facing a similar kind of issue, real-time graphs are not showing after starting the node js script with the debugger I am observing the following message in developers tool console window.


> main.js:630 Refused to load the script 'https://webviewview-vscode-js-profile-flame-realtime.vscode-webview-test.com/vscode-resource/file///Users/----/.vscode/extensions/ms-vscode.vscode-js-profile-flame-0.0.20/out/realtime.bundle.js' because it violates the following Content Security Policy directive: "script-src 'nonce-0.5420808713594358'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.


```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (3 days ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0
```

**Comment by connor4312** [comment] 2021-05-17 16:32
Thanks, just pushed a fix for that

**Comment by oguimbal** [comment] 2021-05-17 16:56
BTW @connor4312 , I dont know if something has been done, but the problem has disapeared for me, somehow. 

I dont know about others, but feel free to close this issue 😁

**Comment by organic-scholar** [comment] 2021-05-17 21:44
@connor4312 Thanks for the fix received the update, it working now

**Comment by connor4312** [comment] 2021-05-17 21:59
Ok, thanks for confirming.

We've made many changes to web views which should be more reliable nowadays. Closing this unless I hear of ongoing issues.

**Closed by connor4312** 2021-05-17 21:59 UTC
